{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hub.fullname" . }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hub.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
      {{- if .Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.monitoring.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.monitoring.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
  {{- if .Values.monitoring.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.monitoring.serviceMonitor.namespaceSelector | nindent 4 }}
  {{- end }}
{{- end }}
