import { NextRequest, NextResponse } from 'next/server';

interface AlertData {
  id: string;
  type: 'error' | 'warning' | 'info';
  metric: string;
  threshold: number;
  currentValue: number;
  timestamp: string;
  message: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  environment: string;
  url: string;
  userAgent: string;
}

export async function POST(request: NextRequest) {
  try {
    const alert: AlertData = await request.json();

    // Validate required fields
    if (!alert.id || !alert.type || !alert.message || !alert.severity) {
      return NextResponse.json(
        { error: 'Missing required alert fields' },
        { status: 400 }
      );
    }

    console.log(`🚨 ${alert.severity.toUpperCase()} ALERT:`, {
      id: alert.id,
      type: alert.type,
      metric: alert.metric,
      message: alert.message,
      value: alert.currentValue,
      threshold: alert.threshold,
      url: alert.url,
      timestamp: alert.timestamp
    });

    // In production, you would:
    // 1. Store alert in database
    // 2. Send to alerting service (PagerDuty, Slack, etc.)
    // 3. Escalate based on severity
    // 4. Track alert resolution

    // Example: Send to Slack webhook
    if (process.env.SLACK_WEBHOOK_URL && alert.severity === 'critical') {
      await sendSlackAlert(alert);
    }

    // Example: Send email for high severity alerts
    if (alert.severity === 'critical' || alert.severity === 'high') {
      await sendEmailAlert(alert);
    }

    return NextResponse.json({
      success: true,
      alertId: alert.id,
      timestamp: new Date().toISOString(),
      message: 'Alert processed and notifications sent'
    });

  } catch (error) {
    console.error('Failed to process alert:', error);
    return NextResponse.json(
      { error: 'Failed to process alert' },
      { status: 500 }
    );
  }
}

async function sendSlackAlert(alert: AlertData) {
  if (!process.env.SLACK_WEBHOOK_URL) return;

  const color = {
    critical: 'danger',
    high: 'warning',
    medium: 'warning',
    low: 'good'
  }[alert.severity] || 'warning';

  const payload = {
    text: `🚨 ${alert.severity.toUpperCase()} Alert: ${alert.message}`,
    attachments: [{
      color,
      fields: [
        {
          title: 'Metric',
          value: alert.metric,
          short: true
        },
        {
          title: 'Current Value',
          value: alert.currentValue?.toString() || 'N/A',
          short: true
        },
        {
          title: 'Threshold',
          value: alert.threshold?.toString() || 'N/A',
          short: true
        },
        {
          title: 'Environment',
          value: alert.environment,
          short: true
        },
        {
          title: 'URL',
          value: alert.url,
          short: false
        },
        {
          title: 'Time',
          value: alert.timestamp,
          short: true
        }
      ],
      footer: 'CODAI Monitoring',
      ts: Math.floor(Date.parse(alert.timestamp) / 1000)
    }]
  };

  try {
    const response = await fetch(process.env.SLACK_WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      console.error('Failed to send Slack alert:', response.statusText);
    }
  } catch (error) {
    console.error('Error sending Slack alert:', error);
  }
}

async function sendEmailAlert(alert: AlertData) {
  // In production, you would integrate with an email service like:
  // - SendGrid
  // - AWS SES
  // - Mailgun
  // - Nodemailer with SMTP

  console.log(`📧 Email alert would be sent for: ${alert.message}`);

  // Example email content
  const emailContent = {
    to: process.env.ALERT_EMAIL_RECIPIENTS?.split(',') || ['alerts@codai.com'],
    subject: `🚨 ${alert.severity.toUpperCase()} Alert - CODAI Coming Soon Page`,
    html: `
      <h2>🚨 ${alert.severity.toUpperCase()} Alert</h2>
      <p><strong>Message:</strong> ${alert.message}</p>
      <p><strong>Metric:</strong> ${alert.metric}</p>
      <p><strong>Current Value:</strong> ${alert.currentValue}</p>
      <p><strong>Threshold:</strong> ${alert.threshold}</p>
      <p><strong>Environment:</strong> ${alert.environment}</p>
      <p><strong>URL:</strong> <a href="${alert.url}">${alert.url}</a></p>
      <p><strong>Time:</strong> ${alert.timestamp}</p>
      <p><strong>Alert ID:</strong> ${alert.id}</p>
      
      <hr>
      <p><em>This alert was generated by the CODAI monitoring system.</em></p>
    `,
    text: `
      CRITICAL Alert: ${alert.message}
      
      Metric: ${alert.metric}
      Current Value: ${alert.currentValue}
      Threshold: ${alert.threshold}
      Environment: ${alert.environment}
      URL: ${alert.url}
      Time: ${alert.timestamp}
      Alert ID: ${alert.id}
    `
  };

  // In production, send the email here
  return emailContent;
}

export async function GET() {
  // Return recent alerts for dashboard

  const mockAlerts = [
    {
      id: 'alert-001',
      type: 'warning',
      metric: 'lcp',
      threshold: 2500,
      currentValue: 2750,
      timestamp: new Date(Date.now() - 300000).toISOString(), // 5 minutes ago
      message: 'LCP (2750ms) exceeded threshold (2500ms)',
      severity: 'medium',
      status: 'active'
    },
    {
      id: 'alert-002',
      type: 'error',
      metric: 'error_rate',
      threshold: 10,
      currentValue: 15,
      timestamp: new Date(Date.now() - 600000).toISOString(), // 10 minutes ago
      message: 'Error rate (15/min) exceeded threshold (10/min)',
      severity: 'high',
      status: 'resolved'
    },
    {
      id: 'alert-003',
      type: 'info',
      metric: 'bounce_rate',
      threshold: 0.4,
      currentValue: 0.45,
      timestamp: new Date(Date.now() - 1200000).toISOString(), // 20 minutes ago
      message: 'Bounce rate (45%) above normal (40%)',
      severity: 'low',
      status: 'active'
    }
  ];

  return NextResponse.json({
    alerts: mockAlerts,
    summary: {
      total: mockAlerts.length,
      active: mockAlerts.filter(a => a.status === 'active').length,
      resolved: mockAlerts.filter(a => a.status === 'resolved').length,
      critical: mockAlerts.filter(a => a.severity === 'critical').length,
      high: mockAlerts.filter(a => a.severity === 'high').length
    },
    timestamp: new Date().toISOString()
  }, {
    headers: {
      'Cache-Control': 'public, s-maxage=30, stale-while-revalidate=60'
    }
  });
}