/**
 * MemorAI Memory Duplicate API
 * Handles duplicating memories
 */

import { NextRequest, NextResponse } from 'next/server';
import cbdClient from '@/lib/cbd-client';
import { ApiResponse, Memory } from '@/types/memory';

// Mock user ID - will be replaced with proper auth
const MOCK_USER_ID = 'user-12345';

interface RouteParams {
    params: {
        id: string;
    };
}

/**
 * POST /api/memories/[id]/duplicate - Duplicate a memory
 */
export async function POST(
    request: NextRequest,
    { params }: RouteParams
): Promise<NextResponse<ApiResponse<Memory>>> {
    try {
        const resolvedParams = await params;
        const { id } = resolvedParams;

        if (!id) {
            return NextResponse.json({
                success: false,
                error: {
                    code: 'VALIDATION_ERROR',
                    message: 'Memory ID is required',
                },
            }, { status: 400 });
        }

        // Get existing memory using findById
        const memory = await cbdClient.findById('memories', id);
        if (!memory) {
            return NextResponse.json({
                success: false,
                error: {
                    code: 'NOT_FOUND',
                    message: 'Memory not found',
                },
            }, { status: 404 });
        }

        // Check if memory belongs to current user
        if (memory.userId !== MOCK_USER_ID) {
            return NextResponse.json({
                success: false,
                error: {
                    code: 'FORBIDDEN',
                    message: 'Access denied',
                },
            }, { status: 403 });
        }

        // Create duplicate with new content and timestamp
        const duplicatedMemory: Memory = {
            ...memory,
            id: undefined, // Will be generated by CBD
            content: `${memory.content} (Copy)`,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            duplicatedFrom: id,
            duplicatedAt: new Date().toISOString(),
            status: 'active', // Reset status for duplicated memory
        };

        // Remove fields that shouldn't be duplicated
        delete duplicatedMemory.archivedAt;
        delete duplicatedMemory.restoredAt;

        // Store duplicated memory
        const storeResult = await cbdClient.storeDocument('memories', duplicatedMemory);
        if (!storeResult.success || !storeResult.data?.result) {
            return NextResponse.json({
                success: false,
                error: {
                    code: 'INTERNAL_ERROR',
                    message: 'Failed to duplicate memory',
                },
            }, { status: 500 });
        }

        const finalMemory = {
            ...duplicatedMemory,
            id: storeResult.data.result // Use the 'result' field from CBD response
        };

        return NextResponse.json({
            success: true,
            data: finalMemory,
        });

    } catch (error) {
        console.error('Duplicate memory API error:', error);
        return NextResponse.json({
            success: false,
            error: {
                code: 'INTERNAL_ERROR',
                message: error instanceof Error ? error.message : 'Failed to duplicate memory',
            },
        }, { status: 500 });
    }
}
