import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import dts from 'vite-plugin-dts'
import { resolve } from 'path'
import { visualizer } from 'rollup-plugin-visualizer'

export default defineConfig({
  plugins: [
    react({
      jsxImportSource: 'react',
      babel: {
        plugins: [
          ['babel-plugin-react-compiler', {}],
        ],
      },
    }),
    dts({
      insertTypesEntry: true,
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/**/*.spec.ts',
        'src/**/*.spec.tsx',
        'src/**/*.stories.ts',
        'src/**/*.stories.tsx',
        'node_modules',
        'dist',
      ],
    }),
    visualizer({
      filename: 'dist/stats.html',
      open: false,
      gzipSize: true,
      brotliSize: true,
    }),
  ],
  build: {
    lib: {
      entry: {
        index: resolve(__dirname, 'src/index.ts'),
        patterns: resolve(__dirname, 'src/patterns/index.ts'),
        state: resolve(__dirname, 'src/state/index.ts'),
        hooks: resolve(__dirname, 'src/hooks/index.ts'),
        utils: resolve(__dirname, 'src/utils/index.ts'),
      },
      name: 'CODAIFrontendArchitecture',
      formats: ['es', 'cjs'],
      fileName: (format, entryName) => {
        const extension = format === 'es' ? 'js' : 'cjs'
        return `${entryName}.${extension}`
      },
    },
    rollupOptions: {
      external: [
        'react',
        'react-dom',
        'react/jsx-runtime',
        'next',
        '@tanstack/react-query',
        '@tanstack/react-router',
        'zustand',
        'valtio',
        'jotai',
        'react-hook-form',
        '@hookform/resolvers',
        'zod',
        'framer-motion',
        '@radix-ui/react-dialog',
        '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-popover',
        '@radix-ui/react-tooltip',
        '@radix-ui/react-toast',
        'react-virtualized-auto-sizer',
        'react-window',
        'react-window-infinite-loader',
        '@tanstack/react-virtual',
        'react-intersection-observer',
        'use-gesture',
        'react-use',
        'ahooks',
        'usehooks-ts',
        'react-error-boundary',
        'react-helmet-async',
        'react-hotkeys-hook',
        'immer',
        'lodash-es',
        'date-fns',
        'clsx',
        'tailwind-merge',
        'class-variance-authority',
        'react-spring',
        '@react-spring/web',
        'lottie-react',
        'react-particles',
        'tsparticles',
        'three',
        '@react-three/fiber',
        '@react-three/drei',
        'react-dnd',
        'react-dnd-html5-backend',
        'react-beautiful-dnd',
        '@dnd-kit/core',
        '@dnd-kit/sortable',
        '@dnd-kit/utilities',
        'react-resizable-panels',
        'react-split-pane',
        'react-grid-layout',
        'react-mosaic-component',
        'cmdk',
        'sonner',
        'vaul',
        'emblor',
        'novel',
        '@tiptap/react',
        '@tiptap/starter-kit',
        'monaco-editor',
        '@monaco-editor/react',
        'prismjs',
        'react-syntax-highlighter',
        'react-markdown',
        'rehype-highlight',
        'remark-gfm',
        'lucide-react',
        '@heroicons/react',
        '@tabler/icons-react',
        'react-icons',
        '@codai/ui-components',
      ],
      output: {
        globals: {
          'react': 'React',
          'react-dom': 'ReactDOM',
          'react/jsx-runtime': 'jsxRuntime',
        },
      },
    },
    sourcemap: true,
    minify: 'esbuild',
    target: 'esnext',
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
      '@/patterns': resolve(__dirname, 'src/patterns'),
      '@/state': resolve(__dirname, 'src/state'),
      '@/hooks': resolve(__dirname, 'src/hooks'),
      '@/utils': resolve(__dirname, 'src/utils'),
      '@/types': resolve(__dirname, 'src/types'),
      '@codai/ui-components': resolve(__dirname, '../ui-components/index.ts'),
    },
  },
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'framer-motion',
      'clsx',
      'tailwind-merge',
    ],
  },
  define: {
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  },
})
