directories:
  output: release
  buildResources: build
appId: ro.metu.app
productName: METU
electronVersion: 37.2.3
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: METU Voice AI
portable:
  artifactName: METU-${version}-portable.exe
