apiVersion: v1
kind: Namespace
metadata:
  name: memorai-system
  labels:
    name: memorai-system
    istio-injection: enabled
    app.kubernetes.io/name: memorai-system
    app.kubernetes.io/part-of: memorai-enterprise
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: memorai-enterprise
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: memorai-enterprise
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: memorai-enterprise
