global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Codai Applications
  - job_name: 'codai-apps'
    metrics_path: '/api/metrics'
    static_configs:
      - targets:
        - 'codai:3000'
        - 'memorai:3001'
        - 'bancai:3002'
        - 'fabricai:3003'
        - 'publicai:3004'
        - 'sociai:3005'
        - 'studiai:3006'
        - 'logai:3007'
        - 'cumparai:3008'
        - 'wallet:3009'
    scrape_interval: 30s
    metrics_path: '/api/health'

  # Database monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Application Performance Monitoring
  - job_name: 'apm'
    static_configs:
      - targets: ['apm-server:8200']

  # Custom business metrics
  - job_name: 'business-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['business-metrics:8080']
    scrape_interval: 60s
