version: '3.8'

services:
  bancai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bancai-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - NEXT_PUBLIC_APP_NAME=BancAI Financial Platform
      - NEXT_PUBLIC_APP_URL=http://localhost:3003
      # LogAI Integration
      - LOGAI_API_URL=http://logai:3002
      - LOGAI_API_KEY=${LOGAI_API_KEY}
      # MemorAI Integration
      - MEMORAI_API_URL=http://memorai:3001
      - MEMORAI_API_KEY=${MEMORAI_API_KEY}
      # Database
      - DATABASE_URL=${DATABASE_URL}
      # External APIs
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - memorai
      - logai
    networks:
      - codai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MemorAI Service (placeholder - actual service should be defined in main docker-compose)
  memorai:
    image: codai/memorai:latest
    container_name: memorai-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - codai-network
    restart: unless-stopped

  # LogAI Service (placeholder - actual service should be defined in main docker-compose)
  logai:
    image: codai/logai:latest
    container_name: logai-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - codai-network
    restart: unless-stopped

networks:
  codai-network:
    driver: bridge
    external: false

volumes:
  bancai_node_modules:
  bancai_next:
