{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jucai.fullname" . }}-netpol
  labels:
    {{- include "jucai.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jucai.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    # Allow ingress from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-system
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    
    # Allow ingress from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    
    # Allow ingress from monitoring
    {{- if .Values.monitoring.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: {{ .Values.monitoring.port | default 9090 }}
    {{- end }}
  
  egress:
    # Allow egress to DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow egress to external APIs (HTTPS)
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
    
    # Allow egress to database
    {{- if .Values.database.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.database.name | default "postgresql" }}
      ports:
        - protocol: TCP
          port: {{ .Values.database.port | default 5432 }}
    {{- end }}
    
    # Allow egress to Redis
    {{- if .Values.redis.enabled }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.redis.name | default "redis" }}
      ports:
        - protocol: TCP
          port: {{ .Values.redis.port | default 6379 }}
    {{- end }}
    
    # Custom egress rules
    {{- range .Values.networkPolicy.egress }}
    - to:
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector | nindent 14 }}
        {{- end }}
      {{- if .ports }}
      ports:
        {{- toYaml .ports | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
