apiVersion: v2
name: stocai
description: AI Stock Trading Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/codai-project/stocai
sources:
  - https://github.com/codai-project/stocai
maintainers:
  - name: Codai Team
    email: team@codai.ai
    url: https://codai.ai
keywords:
  - ai
  - codai
  - microservice
  - kubernetes
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
