service: metu-backend

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'us-east-1'}
  environment:
    NODE_ENV: production
    PORT: 8000
    HOST: 0.0.0.0
    API_BASE_PATH: /api
    LOG_LEVEL: info
    # Add other environment variables here, these will be loaded from serverless.env.yml

functions:
  api:
    handler: dist/serverless.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

package:
  patterns:
    - '!node_modules/.bin/**'
    - '!.git/**'
    - '!.env*'
    - '!.vscode/**'
    - '!.serverless/**'
    - '!tests/**'
    - '!coverage/**'
    - '!src/**'
    - 'dist/**'
    - 'package.json'
    - 'pnpm-lock.yaml'

plugins:
  - serverless-offline
