{
  "apiVersion": "autoscaling/v2",
  "kind": "HorizontalPodAutoscaler",
  "metadata": {
    "name": "metu",
    "namespace": "codai-production",
    "labels": {
      "app": "metu",
      "component": "autoscaler",
      "app.kubernetes.io/name": "metu",
      "app.kubernetes.io/component": "autoscaler",
      "app.kubernetes.io/part-of": "codai-ecosystem"
    }
  },
  "spec": {
    "scaleTargetRef": {
      "apiVersion": "apps/v1",
      "kind": "Deployment",
      "name": "metu"
    },
    "minReplicas": 2,
    "maxReplicas": 10,
    "metrics": [
      {
        "type": "Resource",
        "resource": {
          "name": "cpu",
          "target": {
            "type": "Utilization",
            "averageUtilization": 70
          }
        }
      },
      {
        "type": "Resource",
        "resource": {
          "name": "memory",
          "target": {
            "type": "Utilization",
            "averageUtilization": 80
          }
        }
      }
    ]
  }
}