{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stocai.fullname" . }}-secret
  labels:
    {{- include "stocai.labels" . | nindent 4 }}
type: Opaque
data:
  # Database Credentials
  {{- if .Values.secrets.database.username }}
  DATABASE_USERNAME: {{ .Values.secrets.database.username | b64enc }}
  {{- end }}
  {{- if .Values.secrets.database.password }}
  DATABASE_PASSWORD: {{ .Values.secrets.database.password | b64enc }}
  {{- end }}
  
  # Redis Credentials
  {{- if .Values.secrets.redis.password }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc }}
  {{- end }}
  
  # JWT Secret
  {{- if .Values.secrets.jwt.secret }}
  JWT_SECRET: {{ .Values.secrets.jwt.secret | b64enc }}
  {{- end }}
  
  # API Keys
  {{- if .Values.secrets.api.key }}
  API_KEY: {{ .Values.secrets.api.key | b64enc }}
  {{- end }}
  {{- if .Values.secrets.api.secret }}
  API_SECRET: {{ .Values.secrets.api.secret | b64enc }}
  {{- end }}
  
  # External Service Keys
  {{- range $key, $value := .Values.secrets.external }}
  {{ $key | upper }}_KEY: {{ $value | b64enc }}
  {{- end }}
  
  # Custom Secrets
  {{- range $key, $value := .Values.secrets.custom }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
