packages:
  - packages/*
  - apps/*
  - '!apps/web-dashboard-nextjs'
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - prisma
overrides:
  '@codai/shared-ui': link:../../packages/shared-ui
