module.exports = {
    createCanvas: jest.fn(() => ({
        getContext: jest.fn(() => ({
            fillRect: jest.fn(),
            clearRect: jest.fn(),
            drawImage: jest.fn(),
            getImageData: jest.fn(() => ({ data: new Array(4) })),
            putImageData: jest.fn(),
            beginPath: jest.fn(),
            moveTo: jest.fn(),
            lineTo: jest.fn(),
            stroke: jest.fn(),
            fill: jest.fn(),
            arc: jest.fn(),
            rect: jest.fn(),
            save: jest.fn(),
            restore: jest.fn(),
            translate: jest.fn(),
            rotate: jest.fn(),
            scale: jest.fn(),
            fillText: jest.fn(),
            measureText: jest.fn(() => ({ width: 0 })),
        })),
        toBuffer: jest.fn(),
        toDataURL: jest.fn(),
        width: 800,
        height: 600,
    })),
    loadImage: jest.fn(() => Promise.resolve({})),
    registerFont: jest.fn(),
};
