apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: true
    
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    database: "codai-logs-*"
    interval: "Daily"
    timeField: "@timestamp"
    editable: true
    
  - name: Redis
    type: redis-datasource
    url: redis:6379
    access: proxy
    editable: true
