'use client'

import React, { useState } from 'react'
import {
  Music,
  Play,
  Pause,
  Heart,
  Share2,
  Download,
  Plus,
  Users,
  Star,
  Award,
  Eye,
  MessageCircle,
  Calendar,
  Clock,
  TrendingUp,
  Volume2,
  Mic,
  Headphones,
  Globe,
  Filter,
  Search,
  SortAsc,
  Grid,
  List,
  UserPlus,
  UserCheck,
  MoreHorizontal,
  ExternalLink,
  Bookmark,
  Radio,
  Library,
  Settings
} from 'lucide-react'
import { motion } from 'framer-motion'

export default function ArtistsPage() {
  const [viewMode, setViewMode] = useState('grid')
  const [filterGenre, setFilterGenre] = useState('all')
  const [sortBy, setSortBy] = useState('popularity')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedArtist, setSelectedArtist] = useState(null)

  const artistStats = [
    { icon: Users, label: 'Total Artists', value: '2,847', change: '+156', color: 'text-purple-600' },
    { icon: Star, label: 'Verified Artists', value: '89', change: '+12', color: 'text-blue-600' },
    { icon: TrendingUp, label: 'Rising Stars', value: '234', change: '+45', color: 'text-green-600' },
    { icon: Award, label: 'Featured Artists', value: '67', change: '+8', color: 'text-pink-600' }
  ]

  const artists = [
    {
      id: 1,
      name: 'AI Composer X',
      bio: 'Pioneer in electronic AI music generation with a focus on atmospheric soundscapes',
      genre: 'Electronic',
      subGenres: ['Ambient', 'Synthwave', 'IDM'],
      followers: '45.2K',
      monthlyListeners: '89.4K',
      tracks: 234,
      albums: 12,
      playlists: 89,
      verified: true,
      isFollowing: false,
      joinDate: '2023-08-15',
      lastActive: '2 hours ago',
      topTrack: 'Digital Horizons',
      avatar: '🤖',
      color: 'from-blue-500 to-purple-500',
      popularity: 94,
      country: 'Global AI',
      label: 'AI Records'
    },
    {
      id: 2,
      name: 'Neural Soundscape',
      bio: 'Creating immersive ambient experiences through deep learning algorithms',
      genre: 'Ambient',
      subGenres: ['Drone', 'Nature', 'Meditation'],
      followers: '32.8K',
      monthlyListeners: '67.2K',
      tracks: 189,
      albums: 8,
      playlists: 156,
      verified: true,
      isFollowing: true,
      joinDate: '2023-06-20',
      lastActive: '1 day ago',
      topTrack: 'Ethereal Dreams',
      avatar: '🧠',
      color: 'from-green-500 to-blue-500',
      popularity: 87,
      country: 'Global AI',
      label: 'Mindful Music'
    },
    {
      id: 3,
      name: 'Future Bass AI',
      bio: 'High-energy electronic music powered by cutting-edge AI technology',
      genre: 'Electronic',
      subGenres: ['Future Bass', 'Dubstep', 'Trap'],
      followers: '67.1K',
      monthlyListeners: '123.5K',
      tracks: 156,
      albums: 15,
      playlists: 234,
      verified: true,
      isFollowing: false,
      joinDate: '2023-03-10',
      lastActive: '5 hours ago',
      topTrack: 'Quantum Beats',
      avatar: '🎵',
      color: 'from-purple-500 to-pink-500',
      popularity: 96,
      country: 'Global AI',
      label: 'Bass Network'
    },
    {
      id: 4,
      name: 'Classical AI',
      bio: 'Redefining classical music through AI composition and orchestration',
      genre: 'Classical',
      subGenres: ['Orchestral', 'Chamber', 'Solo Piano'],
      followers: '28.9K',
      monthlyListeners: '45.7K',
      tracks: 87,
      albums: 6,
      playlists: 67,
      verified: true,
      isFollowing: true,
      joinDate: '2023-09-05',
      lastActive: '3 hours ago',
      topTrack: 'Midnight Symphony',
      avatar: '🎼',
      color: 'from-indigo-500 to-purple-500',
      popularity: 82,
      country: 'Global AI',
      label: 'Classical Vision'
    },
    {
      id: 5,
      name: 'Street Beats AI',
      bio: 'Urban sounds and hip-hop beats generated by street-smart AI algorithms',
      genre: 'Hip Hop',
      subGenres: ['Trap', 'Boom Bap', 'Lo-Fi'],
      followers: '54.3K',
      monthlyListeners: '98.6K',
      tracks: 278,
      albums: 11,
      playlists: 189,
      verified: false,
      isFollowing: false,
      joinDate: '2023-07-12',
      lastActive: '1 hour ago',
      topTrack: 'Urban Flow',
      avatar: '🏙️',
      color: 'from-orange-500 to-red-500',
      popularity: 89,
      country: 'Global AI',
      label: 'Independent'
    },
    {
      id: 6,
      name: 'Nature AI',
      bio: 'Capturing the essence of nature through AI-generated organic soundscapes',
      genre: 'Ambient',
      subGenres: ['Nature', 'Field Recording', 'Binaural'],
      followers: '71.8K',
      monthlyListeners: '134.2K',
      tracks: 345,
      albums: 18,
      playlists: 267,
      verified: true,
      isFollowing: true,
      joinDate: '2023-04-18',
      lastActive: '30 minutes ago',
      topTrack: 'Ocean Waves',
      avatar: '🌊',
      color: 'from-blue-500 to-teal-500',
      popularity: 91,
      country: 'Global AI',
      label: 'Natural Records'
    }
  ]

  const quickActions = [
    {
      title: 'Follow Trending',
      description: 'Discover rising AI artists',
      icon: TrendingUp,
      action: 'trending',
      color: 'bg-gradient-to-r from-green-500 to-blue-500'
    },
    {
      title: 'Browse Genres',
      description: 'Explore by music style',
      icon: Library,
      action: 'genres',
      color: 'bg-gradient-to-r from-purple-500 to-pink-500'
    },
    {
      title: 'AI Collaborations',
      description: 'Artists working together',
      icon: Users,
      action: 'collaborations',
      color: 'bg-gradient-to-r from-blue-500 to-purple-500'
    },
    {
      title: 'New Releases',
      description: 'Latest artist uploads',
      icon: Calendar,
      action: 'releases',
      color: 'bg-gradient-to-r from-pink-500 to-red-500'
    }
  ]

  const filteredArtists = artists.filter(artist => {
    const matchesSearch = artist.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      artist.bio.toLowerCase().includes(searchQuery.toLowerCase()) ||
      artist.genre.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesGenre = filterGenre === 'all' || artist.genre.toLowerCase() === filterGenre.toLowerCase()
    return matchesSearch && matchesGenre
  })

  const sortedArtists = [...filteredArtists].sort((a, b) => {
    switch (sortBy) {
      case 'name': return a.name.localeCompare(b.name)
      case 'followers': return parseInt(b.followers.replace('K', '000').replace('.', '')) - parseInt(a.followers.replace('K', '000').replace('.', ''))
      case 'tracks': return b.tracks - a.tracks
      case 'popularity': return b.popularity - a.popularity
      case 'recent': return new Date(b.lastActive) - new Date(a.lastActive)
      default: return b.popularity - a.popularity
    }
  })

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-blue-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-purple-100 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4">
              <div className="bg-gradient-to-r from-purple-600 to-pink-600 p-2 rounded-xl">
                <Users className="h-6 w-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                  Artists
                </h1>
                <p className="text-sm text-gray-600">Discover AI music creators</p>
              </div>
            </div>

            <div className="flex items-center space-x-4">
              <div className="relative">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
                <input
                  type="text"
                  placeholder="Search artists..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10 pr-4 py-2 bg-gray-100 border-0 rounded-lg focus:ring-2 focus:ring-purple-500 focus:bg-white w-64"
                />
              </div>
              <button className="p-2 text-gray-600 hover:text-purple-600 hover:bg-purple-50 rounded-lg transition-colors">
                <Settings className="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Artist Stats */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {artistStats.map((stat, index) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
              className="bg-white/80 backdrop-blur-sm rounded-xl p-6 border border-purple-100 hover:border-purple-200 transition-all"
            >
              <div className="flex items-center justify-between">
                <stat.icon className={`h-8 w-8 ${stat.color}`} />
                <span className="text-green-600 text-sm font-medium">+{stat.change}</span>
              </div>
              <div className="mt-4">
                <h3 className="text-2xl font-bold text-gray-900">{stat.value}</h3>
                <p className="text-gray-600 text-sm">{stat.label}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Quick Actions */}
        <div className="bg-white/80 backdrop-blur-sm rounded-xl p-6 border border-purple-100 mb-8">
          <h2 className="text-xl font-semibold text-gray-900 mb-6">Quick Actions</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {quickActions.map((action, index) => (
              <motion.div
                key={action.title}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: index * 0.1 }}
                className="text-center group cursor-pointer"
              >
                <div className={`${action.color} rounded-xl p-6 mb-4 group-hover:scale-105 transition-transform`}>
                  <action.icon className="h-8 w-8 text-white mx-auto" />
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">{action.title}</h3>
                <p className="text-gray-600 text-sm">{action.description}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Filters and Controls */}
        <div className="bg-white/80 backdrop-blur-sm rounded-xl p-6 border border-purple-100 mb-8">
          <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <Filter className="h-4 w-4 text-gray-600" />
                <select
                  value={filterGenre}
                  onChange={(e) => setFilterGenre(e.target.value)}
                  className="bg-gray-50 border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500"
                >
                  <option value="all">All Genres</option>
                  <option value="electronic">Electronic</option>
                  <option value="ambient">Ambient</option>
                  <option value="classical">Classical</option>
                  <option value="hip hop">Hip Hop</option>
                  <option value="jazz">Jazz</option>
                </select>
              </div>
              <div className="flex items-center space-x-2">
                <SortAsc className="h-4 w-4 text-gray-600" />
                <select
                  value={sortBy}
                  onChange={(e) => setSortBy(e.target.value)}
                  className="bg-gray-50 border border-gray-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-purple-500"
                >
                  <option value="popularity">Popularity</option>
                  <option value="name">Name</option>
                  <option value="followers">Followers</option>
                  <option value="tracks">Track Count</option>
                  <option value="recent">Recently Active</option>
                </select>
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <button
                onClick={() => setViewMode('grid')}
                className={`p-2 rounded-lg transition-colors ${viewMode === 'grid'
                    ? 'bg-purple-100 text-purple-600'
                    : 'text-gray-600 hover:text-purple-600 hover:bg-purple-50'
                  }`}
              >
                <Grid className="h-4 w-4" />
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`p-2 rounded-lg transition-colors ${viewMode === 'list'
                    ? 'bg-purple-100 text-purple-600'
                    : 'text-gray-600 hover:text-purple-600 hover:bg-purple-50'
                  }`}
              >
                <List className="h-4 w-4" />
              </button>
            </div>
          </div>
        </div>

        {/* Artists Grid/List */}
        <div className="bg-white/80 backdrop-blur-sm rounded-xl p-6 border border-purple-100">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-xl font-semibold text-gray-900">
              AI Artists ({sortedArtists.length})
            </h2>
            <button className="bg-gradient-to-r from-purple-600 to-pink-600 text-white px-4 py-2 rounded-lg font-medium hover:scale-105 transition-transform">
              <Plus className="h-4 w-4 inline mr-2" />
              Submit Artist
            </button>
          </div>

          {viewMode === 'grid' ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {sortedArtists.map((artist, index) => (
                <motion.div
                  key={artist.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="group cursor-pointer"
                >
                  <div className="relative overflow-hidden rounded-xl bg-white border border-purple-100 hover:border-purple-200 transition-all hover:shadow-lg">
                    {/* Artist Cover */}
                    <div className={`h-48 bg-gradient-to-br ${artist.color} relative overflow-hidden`}>
                      <div className="absolute inset-0 flex items-center justify-center text-6xl text-white/90">
                        {artist.avatar}
                      </div>
                      {/* Badges */}
                      <div className="absolute top-4 left-4 flex flex-wrap gap-2">
                        {artist.verified && (
                          <div className="flex items-center space-x-1 bg-blue-500 text-white text-xs px-2 py-1 rounded-full">
                            <Award className="h-3 w-3" />
                            <span>Verified</span>
                          </div>
                        )}
                        <div className="bg-black/20 backdrop-blur-sm text-white text-xs px-2 py-1 rounded-full">
                          {artist.popularity}% popularity
                        </div>
                      </div>
                      {/* Follow Button Overlay */}
                      <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button className={`px-3 py-1 rounded-full text-xs font-medium transition-all ${artist.isFollowing
                            ? 'bg-white/20 backdrop-blur-sm text-white border border-white/30'
                            : 'bg-white text-purple-600 hover:bg-purple-50'
                          }`}>
                          {artist.isFollowing ? (
                            <>
                              <UserCheck className="h-3 w-3 inline mr-1" />
                              Following
                            </>
                          ) : (
                            <>
                              <UserPlus className="h-3 w-3 inline mr-1" />
                              Follow
                            </>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Artist Info */}
                    <div className="p-6">
                      <div className="flex justify-between items-start mb-3">
                        <div className="flex-1">
                          <div className="flex items-center space-x-2 mb-1">
                            <h3 className="font-bold text-gray-900 text-lg">{artist.name}</h3>
                            {artist.verified && (
                              <Award className="h-4 w-4 text-blue-500" />
                            )}
                          </div>
                          <p className="text-gray-600 text-sm mb-2">{artist.bio}</p>
                          <div className="flex flex-wrap gap-1 mb-3">
                            <span className="bg-purple-100 text-purple-700 px-2 py-1 rounded text-xs">{artist.genre}</span>
                            {artist.subGenres.slice(0, 2).map((subGenre) => (
                              <span key={subGenre} className="bg-gray-100 text-gray-600 px-2 py-1 rounded text-xs">{subGenre}</span>
                            ))}
                          </div>
                        </div>
                      </div>

                      <div className="grid grid-cols-3 gap-4 text-center mb-4">
                        <div>
                          <div className="font-semibold text-gray-900">{artist.followers}</div>
                          <div className="text-xs text-gray-600">Followers</div>
                        </div>
                        <div>
                          <div className="font-semibold text-gray-900">{artist.tracks}</div>
                          <div className="text-xs text-gray-600">Tracks</div>
                        </div>
                        <div>
                          <div className="font-semibold text-gray-900">{artist.albums}</div>
                          <div className="text-xs text-gray-600">Albums</div>
                        </div>
                      </div>

                      <div className="flex items-center justify-between mb-4">
                        <div className="text-sm text-gray-600">
                          <div className="flex items-center space-x-1 mb-1">
                            <Headphones className="h-3 w-3" />
                            <span>{artist.monthlyListeners} monthly listeners</span>
                          </div>
                          <div className="flex items-center space-x-1">
                            <Clock className="h-3 w-3" />
                            <span>{artist.lastActive}</span>
                          </div>
                        </div>
                      </div>

                      <div className="flex items-center justify-between">
                        <div className="text-sm text-gray-600">
                          <div className="font-medium">Top Track:</div>
                          <div>{artist.topTrack}</div>
                        </div>
                        <div className="flex items-center space-x-2">
                          <button className="p-2 text-gray-600 hover:text-purple-600 rounded-lg transition-colors">
                            <Play className="h-4 w-4" />
                          </button>
                          <button className="p-2 text-gray-600 hover:text-blue-600 rounded-lg transition-colors">
                            <Share2 className="h-4 w-4" />
                          </button>
                          <button className="p-2 text-gray-600 hover:text-gray-700 rounded-lg transition-colors">
                            <MoreHorizontal className="h-4 w-4" />
                          </button>
                        </div>
                      </div>

                      <div className="mt-4 pt-4 border-t border-gray-100">
                        <div className="flex justify-between items-center text-xs text-gray-500">
                          <span>{artist.label}</span>
                          <span>Joined {new Date(artist.joinDate).toLocaleDateString()}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          ) : (
            <div className="space-y-4">
              {sortedArtists.map((artist, index) => (
                <motion.div
                  key={artist.id}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="flex items-center space-x-4 p-4 rounded-lg hover:bg-purple-50 transition-colors group"
                >
                  <div className={`w-20 h-20 bg-gradient-to-br ${artist.color} rounded-xl flex items-center justify-center text-white text-2xl flex-shrink-0`}>
                    {artist.avatar}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center space-x-2 mb-1">
                      <h3 className="font-semibold text-gray-900">{artist.name}</h3>
                      {artist.verified && <Award className="h-4 w-4 text-blue-500 flex-shrink-0" />}
                      <span className="bg-purple-100 text-purple-700 px-2 py-1 rounded text-xs">{artist.genre}</span>
                    </div>
                    <p className="text-gray-600 text-sm mb-2 line-clamp-1">{artist.bio}</p>
                    <div className="flex items-center space-x-4 text-xs text-gray-500">
                      <span>{artist.followers} followers</span>
                      <span>{artist.tracks} tracks</span>
                      <span>{artist.monthlyListeners} monthly listeners</span>
                      <span>{artist.lastActive}</span>
                    </div>
                  </div>

                  <div className="flex items-center space-x-2">
                    <div className="text-right mr-4">
                      <div className="text-sm font-medium text-gray-900">{artist.popularity}%</div>
                      <div className="text-xs text-gray-600">Popularity</div>
                    </div>
                    <button className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${artist.isFollowing
                        ? 'bg-purple-100 text-purple-600 hover:bg-purple-200'
                        : 'bg-purple-600 text-white hover:bg-purple-700'
                      }`}>
                      {artist.isFollowing ? (
                        <>
                          <UserCheck className="h-4 w-4 inline mr-1" />
                          Following
                        </>
                      ) : (
                        <>
                          <UserPlus className="h-4 w-4 inline mr-1" />
                          Follow
                        </>
                      )}
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white/80 backdrop-blur-sm border-t border-purple-100 mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <div className="bg-gradient-to-r from-purple-600 to-pink-600 p-2 rounded-lg">
                <Users className="h-5 w-5 text-white" />
              </div>
              <span className="font-semibold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                MuzicAI Artists
              </span>
            </div>
            <p className="text-gray-600 text-sm mb-4">
              Discover and support AI music creators
            </p>
            <div className="flex items-center justify-center space-x-6 text-sm text-gray-500">
              <a href="#" className="hover:text-purple-600 transition-colors">Submit Music</a>
              <a href="#" className="hover:text-purple-600 transition-colors">Artist Guidelines</a>
              <a href="#" className="hover:text-purple-600 transition-colors">Verification</a>
              <a href="#" className="hover:text-purple-600 transition-colors">Support</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
