{
  "apiVersion": "monitoring.coreos.com/v1",
  "kind": "ServiceMonitor",
  "metadata": {
    "name": "kodex",
    "namespace": "codai-production",
    "labels": {
      "app": "kodex",
      "component": "monitoring",
      "app.kubernetes.io/name": "kodex",
      "app.kubernetes.io/component": "monitoring",
      "app.kubernetes.io/part-of": "codai-ecosystem"
    }
  },
  "spec": {
    "selector": {
      "matchLabels": {
        "app": "kodex"
      }
    },
    "endpoints": [
      {
        "port": "http",
        "path": "/metrics",
        "interval": "30s"
      }
    ]
  }
}